trigger:
  - master

stages:
  - stage: Apply_Infrastructure
    jobs:
      - job: Apply_Terraform
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.14.3'

          - script: |
              cd dev/

              terraform init
              terraform apply infra_plan --auto-approve
